pracuj_job_keywords = [
    "data",
    "analyst",
    "analityk",
    "business",
    "python",
    "database",
    "baz danych",
    "product",
]

pracuj_excluded_keywords = [
    "senior",
    "starszy",
    "german",
    "italian",
    "czech",
    "portuguese",
    "dutch",
    "french",
    "turkish",
    "bulgarian",
    "lithuanian",
    "latvian",
    "russian",
    "finnish",
    "danish",
    "norwegian",
    "swedish",
    "niemiecki",
    "francuski",
    "rosyjski",
    "romanian",
    "slovenian",
    "slovakian",
    "słoweński",
    "słowacki",
    "hr ",
    " hr ",
    "sr "
    " sr ",
    "manager",
    "head",
    "kierownik",
    "graduate programme",
    "graduate",
    "production",
    "machine learning",
    "spark",
    "java",
    "lead",
    "doświadczon",
    "doświadczeni",
    "gcp",
    "react",
    "cloud",
    "power platform",
    " rpa ",
    "rpa ",
    " rpa",
    "tableau",
    "qlik",
    "django",
    "fullstack",
    "full stack",
    "oracle",
    "3d",
    "ecommerce",
    "sap",
    "US hours",
    "helpdesk",
    "help desk",
    "service desk",
    "sharepoint",
    "share point",
    "soc",
]

pracuj_desired_workplaces = [
    "kraków",
    "małopolskie",
    "warszawa",
    "mazowieckie",
    "wrocław",
]